### ISSUE TITLE
loadMore function not being called after initial call, even when hasMore is true.

### ISSUE THREAD

**Issue by mislagle** [guillaumervls/react-infinite-scroll#26]
the loadMore function is called once, but after that initial call, even when reaching the bottom of the list, the loadMore function is never called again. Can't seem to solve myself, no console errors.

**Comment by calvinchankf** [comment]
Hi @mislagle, did you solve it? I got the same problem. So I implemented it from scratch on my own https://github.com/calvinchankf/ReactRefreshinFiniteTableView

**Comment by danbovey** [comment]
Nice work! I doubt this issue is still a problem for OP, but if anybody finds this and you're looking for a demo, there's a few people now helping to maintain this package at https://github.com/CassetteRocks/react-infinite-scroller

Demo here: http://cassetterocks.github.io/react-infinite-scroller/demo/
